--TAO DATABASE
CREATE DATABASE QL_DIENMAY
ON PRIMARY
(
	NAME= 'QL_PRIMARY',
	FILENAME= 'D:\QL_PRIMARY.mdf',
	SIZE = 30 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 10%
),
FILEGROUP FILE1
(
	NAME= 'QL_FILE1',
	FILENAME= 'D:\QL_FILE1.ndf',
	SIZE = 20 MB,
	MAXSIZE = 50 MB,
	FILEGROWTH = 10%
),
FILEGROUP FILE2
(
	NAME= 'QL_FILE2',
	FILENAME= 'D:\QL_FILE2.ndf',
	SIZE = 10 MB,
	MAXSIZE = 30 MB,
	FILEGROWTH = 5%
)
LOG ON
(
	NAME= 'QL_LOG',
	FILENAME= 'D:\QL_LOG.ldf',
	SIZE = 30 MB,
	MAXSIZE = 100 MB,
	FILEGROWTH = 15%
)
USE QL_DIENMAY
alter database QL_DIENMAY set recovery full
CREATE TABLE NHANVIEN  
(
	MANV CHAR(10)NOT NULL PRIMARY KEY,
	HOTENNV NVARCHAR(50),
	PHAI NVARCHAR(20),
	DIACHI NVARCHAR(50),
	CHUCVU NVARCHAR(30),
	LUONG INT
)ON FILE1
CREATE TABLE KHACHHANG
(
	MAKH CHAR(10)NOT NULL PRIMARY KEY,
	TENKHACH NVARCHAR(50),
	DCHI NVARCHAR(50),
	PHAI NVARCHAR(20),
	DTHOAI CHAR(10),
	LOAIKH INT,
)ON FILE1
GO
CREATE TABLE NHASX
(
	MANSX CHAR(10)NOT NULL PRIMARY KEY,
	TENNSX NVARCHAR(50),
	DCHI NVARCHAR(50),
	DTHOAI CHAR(10)
)ON FILE1
GO
CREATE TABLE NHACC
(
	MANCC CHAR(10)NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(50),
	DCHI NVARCHAR(50),
	DTHOAI CHAR(10)
)ON FILE1
GO
CREATE TABLE HANG
(
	MAHG CHAR(10)NOT NULL PRIMARY KEY,
	TENHG NVARCHAR(50),
	LOAI NVARCHAR(50),
	SOLUONG INT,
	MANSX CHAR(10),
	MANCC CHAR(10),
	TINHTRANG NVARCHAR(20),
	BAOHANH INT,
	CONSTRAINT FK_H_NSX FOREIGN KEY(MANSX) REFERENCES NHASX(MANSX),
	CONSTRAINT FK_H_NCC FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC)
)ON FILE1
GO
CREATE TABLE DONGIA
(
	MAHG CHAR(10)NOT NULL,
	NGAYCN DATE NOT NULL,
	GIA INT,
	PRIMARY KEY(MAHG,NGAYCN),
	CONSTRAINT FK_DG_HG FOREIGN KEY(MAHG) REFERENCES HANG(MAHG)
)ON FILE1
GO
CREATE TABLE PHIEUNHAP
(
	MAPN CHAR(10)NOT NULL PRIMARY KEY,
	NGAYNHAP DATE,
	MANCC CHAR(10),
	MANSX CHAR(10),
	TIENNHAP INT,
	CONSTRAINT FK_PN_NCC FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC),
	CONSTRAINT FK_PN_NSX FOREIGN KEY(MANSX) REFERENCES NHASX(MANSX)
)ON FILE2
GO
CREATE TABLE CHITIETPHIEUNHAP
(
	MAPN CHAR(10)NOT NULL,
	MAHG CHAR(10)NOT NULL,
	SOLUONG INT,
	GIANHAP INT,
	THANHTIEN INT,
	PRIMARY KEY(MAPN,MAHG),
	CONSTRAINT FK_CTPN_PN FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN),
	CONSTRAINT FK_CTPN_HG FOREIGN KEY(MAHG) REFERENCES HANG(MAHG)
)ON FILE2
GO
CREATE TABLE HOADON
(
	MAHD CHAR(10)NOT NULL PRIMARY KEY,
	MANV CHAR(10),
	MAKH CHAR(10),
	NGAYLAP DATE,
	TIENBAN INT,
	GIAMGIA INT,
	THANHTOAN INT,
	CONSTRAINT FK_HD_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)ON FILE2
GO
CREATE TABLE CHITIETHOADON
(
	MAHD CHAR(10)NOT NULL,
	MAHG CHAR(10)NOT NULL,
	SOLUONG INT,
	GIABAN INT,
	THANHTIEN INT,
	PRIMARY KEY(MAHD, MAHG),
	CONSTRAINT FK_CTHD_HD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CTHD_HANG FOREIGN KEY(MAHG) REFERENCES HANG(MAHG)
)ON FILE2
GO
CREATE TABLE PHIEUBAOHANH
(
	MAPHIEUBH CHAR(10)NOT NULL,
	MAHD CHAR(10),
	MAHG CHAR(10),
	NGAYBH DATE,
	NOIDUNG NVARCHAR(100),
	CHIPHI INT,
	CONSTRAINT FK_PBH_HANG FOREIGN KEY(MAHG) REFERENCES HANG(MAHG) 
)ON FILE2
GO
CREATE TABLE GIAMGIA
(
	MAHG CHAR(10)NOT NULL,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE,
	SOTIENGIAM INT,
	PRIMARY KEY(MAHG, NGAYBATDAU),
	CONSTRAINT FK_GIAMGIA_HG FOREIGN KEY(MAHG) REFERENCES HANG(MAHG) 
)ON FILE1
GO
--Tao store procedure cho nhan vien
CREATE PROC PR_NHANVIEN @MANV CHAR(10), @HOTENNV NVARCHAR(50), @PHAI NVARCHAR(20), @DIACHI NVARCHAR(50), @CHUCVU NVARCHAR(30), @LUONG INT
AS
	BEGIN TRY
		IF((SELECT COUNT(*) FROM NHANVIEN WHERE MANV=@MANV)=1)
			BEGIN
				PRINT 'MA NHAN VIEN BI TRUNG'
				ROLLBACK TRAN
				RETURN
			END
		IF(@PHAI != 'NAM' OR @PHAI != 'NU')
			SET @PHAI = 'KHONG XAC DINH'
		IF(@CHUCVU != 'NHAN VIEN' OR @CHUCVU != 'QUAN LY' OR @CHUCVU != 'GIAM DOC')
			SET @CHUCVU = 'NHAN VIEN'
		IF(@LUONG < 0)
			BEGIN
				PRINT 'LUONG NHAP SAI'
				ROLLBACK TRAN
				RETURN
			END
	END TRY
	BEGIN CATCH
		PRINT 'THEM THAT BAI'
		ROLLBACK TRAN
	END CATCH
	INSERT INTO NHANVIEN VALUES (@MANV,@HOTENNV,@PHAI,@DIACHI,@CHUCVU,@LUONG)
	COMMIT TRAN
GO
--Tao store procedure cho KHACH HANG

CREATE PROC PR_KHACHHANG @MAKH CHAR(10), @TENKHACH NVARCHAR(50), @DCHI NVARCHAR(50), @PHAI NVARCHAR(20), @DTHOAI CHAR(11),@LOAIKH INT
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM KHACHHANG WHERE MAKH = @MAKH)=1)
	BEGIN
		PRINT 'MA KHACH HANG DA TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF(@PHAI != 'NAM' OR @PHAI != 'NU')
			SET @PHAI = 'KHONG XAC DINH'
	
	IF((SELECT COUNT(*) FROM HOADON WHERE MAKH = @MAKH)=0)
		SET @LOAIKH = 0
	IF((SELECT COUNT(*) FROM HOADON WHERE MAKH = @MAKH)=1)
		SET @LOAIKH = 1
	IF((SELECT COUNT(*) FROM HOADON WHERE MAKH = @MAKH)>1 AND (SELECT COUNT(*) FROM HOADON WHERE MAKH = @MAKH)<5)
		SET @LOAIKH = 2
	IF((SELECT COUNT(*) FROM HOADON WHERE MAKH = @MAKH)>=5)
		SET @LOAIKH = 3
END TRY
BEGIN CATCH
	PRINT 'KHONG THE THEM KHACH HANG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO KHACHHANG VALUES (@MAKH,@TENKHACH,@DCHI,@PHAI,@DTHOAI,@LOAIKH)
	COMMIT TRAN
GO
--Tao store procedure cho NHASX
CREATE PROC PR_NHASX @MANSX CHAR(10),@TENNSX NVARCHAR(50), @DCHI NVARCHAR(50), @DTHOAI CHAR(10)
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM NHASX WHERE MANSX = @MANSX)=1)
	BEGIN
		PRINT 'MA NHA SAN XUAT BI TRUNG'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT 'THEM NHA SAN XUAT KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO NHASX VALUES (@MANSX,@TENNSX,@DCHI,@DTHOAI)
GO
--Tao store procedure cho NHACC
CREATE PROC PR_NHACC @MANCC CHAR(10),@TENNCC NVARCHAR(50), @DCHI NVARCHAR(50), @DTHOAI CHAR(10)
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM NHACC WHERE MANCC = @MANCC)=1)
	BEGIN
		PRINT 'MA NHA CUNG CAP BI TRUNG'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT 'THEM NHA CUNG CAP KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO NHACC VALUES (@MANCC,@TENNCC,@DCHI,@DTHOAI)
GO
--Tao store procedure cho HANG
CREATE PROC PR_HANG @MAHG CHAR(10),@TENHG NVARCHAR(50), @LOAI NVARCHAR(50), @SOLUONG INT, @MANSX CHAR(10), @MANCC CHAR(10), @BAOHANH INT
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM HANG WHERE MAHG = @MAHG) = 1)
	BEGIN
		PRINT 'MA HANG DA TON TAI'
		ROLLBACK TRAN
		RETURN 
	END
	IF(@LOAI != N'DIEN THOAI' AND @LOAI != N'TIVI' AND @LOAI != N'LAPTOP' AND @LOAI != N'DIEN LANH' AND @LOAI != N'GIA DUNG')
	BEGIN
		PRINT 'LOAI HANG KHONG DUNG'
		ROLLBACK TRAN
		RETURN
	END
	IF(@SOLUONG < 0)
	BEGIN
		PRINT 'SO LUONG KHONG HOP LE'
		ROLLBACK TRAN
		RETURN
	END
	IF((SELECT COUNT(*) FROM NHASX WHERE MANSX = @MANSX) = 0)
	BEGIN
		PRINT 'NHA SAN XUAT KHONG TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF((SELECT COUNT(*) FROM NHACC WHERE MANCC = @MANCC) = 0)
	BEGIN
		PRINT 'NHA CUNG CAP KHONG TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF(@BAOHANH<0)
	BEGIN
		PRINT 'THOI GIAN BAO HANH KHONG HOP LE'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT 'THEM HANG KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO HANG(MAHG,TENHG,LOAI,SOLUONG,MANSX,MANCC,BAOHANH) VALUES (@MAHG,@TENHG,@LOAI,@SOLUONG,@MANSX,@MANCC,@BAOHANH)
	COMMIT TRAN
GO
--TAO TRIGGER UPDATE TINH TRANG HANG KHI THEM MOI HOAC UPDATE SO LUONG HANG
CREATE TRIGGER TRG_UPTINHTRANG ON HANG
FOR INSERT, UPDATE
AS
	IF((SELECT SOLUONG FROM HANG WHERE MAHG = (SELECT MAHG FROM inserted)) > 0)
		UPDATE HANG
		SET TINHTRANG = N'CON HANG'
		WHERE MAHG = (SELECT MAHG FROM inserted)
	ELSE
		UPDATE HANG
		SET TINHTRANG = N'HET HANG'
		WHERE MAHG = (SELECT MAHG FROM inserted)
GO
--TAO HAM INPUT: MAHANG, SO LUONG CAN LAY OUTPUT: 1- NEU DU, 0- NEU THIEU
CREATE FUNCTION FUN_CHECKHANGDU(@MAHG CHAR(10),@SOLUONG INT)
RETURNS INT
AS
BEGIN
	DECLARE @KQ INT
	IF((SELECT SOLUONG FROM HANG WHERE MAHG = @MAHG)<@SOLUONG)
		SET @KQ=0
	ELSE 
		SET @KQ=1
	RETURN @KQ
END
GO
--Tao store procedure cho DONGIA
CREATE PROC PR_DONGIA @MAHG CHAR(10),@GIA INT
AS
BEGIN TRY
	IF((SELECT COUNT(*)FROM HANG WHERE MAHG = @MAHG)=0)
	BEGIN
		PRINT 'MAT HANG CHUA TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF(@GIA<0)
	BEGIN
		PRINT 'GIA KHONG HOP LE'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT 'THEM DON GIA THAT BAI'
	ROLLBACK TRAN
END CATCH
	INSERT INTO DONGIA VALUES(@MAHG,GETDATE(),@GIA)
	COMMIT TRAN
GO
--TAO TRIGGER TU DONG CAP NHAT NGAY KHI THEM HOAC SUA DON GIA
CREATE TRIGGER TRG_SETDATEFORNGAYCN ON DONGIA
FOR INSERT,UPDATE
AS
	UPDATE DONGIA
	SET NGAYCN = GETDATE()
	WHERE MAHG = (SELECT MAHG FROM inserted)
GO
--Tao store procedure cho PHIEU NHAP
CREATE PROC PR_PHIEUNHAP @MAPN CHAR(10),@MANCC CHAR(10),@MANSX CHAR(10)
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM PHIEUNHAP WHERE MAPN = @MAPN) = 1)
	BEGIN
		PRINT 'PHIEU NHAP DA TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF((SELECT COUNT(*) FROM NHASX WHERE MANSX = @MANSX) = 0)
	BEGIN
		PRINT 'NHA SAN XUAT KHONG TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF((SELECT COUNT(*) FROM NHACC WHERE MANCC = @MANCC) = 0)
	BEGIN
		PRINT 'NHA CUNG CAP KHONG TON TAI'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT'THEM PHIEU NHAP KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO PHIEUNHAP VALUES (@MAPN,GETDATE(),@MANCC,@MANSX,0)
	COMMIT TRAN
GO
--TAO TRIGGER CAP NHAT THANH TIEN CHO PHIEU NHAP
CREATE TRIGGER TRG_UPTHANHTIENPN ON CHITIETPHIEUNHAP
FOR INSERT,UPDATE
AS
	UPDATE PHIEUNHAP
	SET TIENNHAP = (SELECT THANHTIEN FROM CHITIETPHIEUNHAP WHERE MAPN = (SELECT MAPN FROM inserted) AND MAHG = (SELECT MAHG FROM inserted))
	WHERE MAPN = (SELECT MAPN FROM inserted)
GO
--Tao store procedure cho CHI TIET PHIEU NHAP
CREATE PROC PR_CTPN @MAPN CHAR(10),@MAHG CHAR(10),@SOLUONG INT
AS 
BEGIN TRY
	IF((SELECT COUNT(*) FROM CHITIETPHIEUNHAP WHERE MAPN = @MAPN AND MAHG=@MAHG)=1)
	BEGIN
		PRINT'MA PHIEU NHAP VA MA HANG KHONG HOP LE'
		ROLLBACK TRAN
		RETURN
	END
	IF((SELECT COUNT(*)FROM PHIEUNHAP WHERE MAPN = @MAPN)=0)
	BEGIN
		PRINT 'MAT PHIEU CHUA TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF((SELECT COUNT(*)FROM HANG WHERE MAHG = @MAHG)=0)
	BEGIN
		PRINT 'MAT HANG CHUA TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF(@SOLUONG<0)
	BEGIN
		PRINT 'SO LUONG KHONG HOP LE'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT 'THEM CHI TIET PHIEU NHAP KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO  CHITIETPHIEUNHAP(MAPN,MAHG,SOLUONG) VALUES (@MAPN,@MAHG,@SOLUONG)
	COMMIT TRAN
GO
--TRIGGER  CUA CHI TIET PHIEU NHAP
CREATE TRIGGER TRG_CTPN ON CHITIETPHIEUNHAP
FOR INSERT, UPDATE
AS
	UPDATE CHITIETPHIEUNHAP
	SET GIANHAP = (SELECT GIA FROM DONGIA WHERE MAHG = (SELECT MAHG FROM inserted))
	WHERE MAPN = (SELECT MAPN FROM inserted) AND MAHG =(SELECT MAHG FROM inserted)
	UPDATE HANG
	SET SOLUONG = SOLUONG + (SELECT SOLUONG FROM inserted)
	WHERE MAHG =(SELECT MAHG FROM inserted)
	UPDATE CHITIETPHIEUNHAP
	SET THANHTIEN =(SELECT SOLUONG FROM inserted)*(SELECT GIA FROM DONGIA WHERE MAHG = (SELECT MAHG FROM inserted))
	WHERE MAPN = (SELECT MAPN FROM inserted) AND MAHG =(SELECT MAHG FROM inserted)
GO
--Tao store procedure cho GIAM GIA
CREATE PROC PR_GIAMGIA @MAHG CHAR(10),@NGAYKETTHUC DATE,@SOTIENGIAM INT
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM GIAMGIA WHERE MAHG =@MAHG AND NGAYBATDAU=GETDATE())=1)
	BEGIN
		PRINT 'MAT HANG NAY DA KHUYEN MAI HOM NAY'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT COUNT(*)FROM HANG WHERE MAHG = @MAHG)=0)
	BEGIN
		PRINT 'MAT HANG CHUA TON TAI'
		ROLLBACK TRAN
		RETURN
	END
	IF(@NGAYKETTHUC<GETDATE())
	BEGIN
		PRINT 'NGAY KET THUC KHONG HOP LE'
		ROLLBACK TRAN
		RETURN
	END
END TRY
BEGIN CATCH
	PRINT 'THEM KHUYEN MAI KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO GIAMGIA VALUES (@MAHG,GETDATE(),@NGAYKETTHUC,@SOTIENGIAM)
COMMIT TRAN
GO
--Tao store procedure cho BAO HANH
CREATE PROC PR_BAOHANH @MAPHIEUBH CHAR(10),@MAHD CHAR(10),@MAHG CHAR(10),@NGAYBH DATE,@NOIDUNG NVARCHAR(100)
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM PHIEUBAOHANH WHERE MAPHIEUBH = @MAPHIEUBH)=1)
	BEGIN
		PRINT 'PHIEU DA TON TAI'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT COUNT(*) FROM HOADON WHERE MAHD = @MAHD)=0)
	BEGIN
		PRINT 'HOA DON KHONG HOP LE'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT COUNT(*) FROM CHITIETHOADON WHERE MAHG = @MAHG AND MAHD=@MAHD)=0)
	BEGIN
		PRINT 'MA HANG KHONG HOP LE'
		ROLLBACK TRAN
		RETURN 
	END
	IF(@NGAYBH<(SELECT NGAYLAP FROM HOADON WHERE MAHD = @MAHD))
	BEGIN
		PRINT 'NGAY BAO HANH KHONG HOP LE'
		ROLLBACK TRAN
		RETURN 
	END
	DECLARE @NGAY DATE,@THANG INT
	SET @NGAY = (SELECT NGAYLAP FROM HOADON WHERE MAHD = @MAHD)
	SET @THANG = (SELECT BAOHANH FROM HANG WHERE MAHG = @MAHG)
	DECLARE @CHIPHI INT
	IF(@NGAYBH < (SELECT DATEADD(MONTH,@THANG,@NGAY)))
		SET @CHIPHI = 0
	ELSE
		SET @CHIPHI = (SELECT THANHTOAN FROM HOADON WHERE MAHD = @MAHD)/2
END TRY
BEGIN CATCH
	PRINT 'THEM KHONG THANH CONG PHIEU BAO HANH'
	ROLLBACK TRAN 
END CATCH
	INSERT INTO PHIEUBAOHANH VALUES (@MAPHIEUBH,@MAHD,@MAHG,@NGAYBH,@NOIDUNG,@CHIPHI)
COMMIT TRAN
GO
--TAO TRIGGER CAP NHAT TIEN BAN CHO HOA DON
CREATE TRIGGER TRG_TIENBAN ON CHITIETHOADON
FOR INSERT, UPDATE
AS
	UPDATE HOADON
	SET TIENBAN = (SELECT SUM(THANHTIEN) FROM CHITIETHOADON WHERE MAHD = (SELECT MAHD FROM inserted))
	WHERE MAHD = (SELECT MAHD FROM inserted)
GO
--TAO TRIGGER CAP NHAT GIAM GIA CHO HOA DON
CREATE TRIGGER TRG_GIAMGIA ON CHITIETHOADON
FOR INSERT, UPDATE
AS
	IF((SELECT COUNT(*) FROM GIAMGIA WHERE MAHG = (SELECT MAHG FROM inserted) AND NGAYKETTHUC > GETDATE()) =1) 
		UPDATE HOADON
		SET GIAMGIA = GIAMGIA + ((SELECT SOTIENGIAM FROM GIAMGIA WHERE MAHG =(SELECT MAHG FROM inserted))*(SELECT SOLUONG FROM inserted))
		WHERE MAHD = (SELECT MAHD FROM inserted)
GO
--TAO TRIGGER CAP NHAT THANH TOAN
CREATE TRIGGER TRG_THANHTOAN ON HOADON
FOR INSERT, UPDATE
AS
	 UPDATE HOADON
	 SET THANHTOAN = (SELECT TIENBAN FROM inserted)-(SELECT GIAMGIA FROM inserted)
	 WHERE MAHD = (SELECT MAHD FROM inserted)
 GO
--Tao store procedure cho HOA DON
CREATE PROC PR_HOADON @MAHD CHAR(10),@MANV CHAR(10),@MAKH CHAR(10)
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM HOADON WHERE MAHD = @MAHD) = 1)
	BEGIN
		PRINT 'MA HOA DON DA TON TAI'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT COUNT(*) FROM NHANVIEN WHERE MANV = @MANV) = 0)
	BEGIN
		PRINT 'NHAN VIEN KHONG TON TAI'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT COUNT(*) FROM KHACHHANG WHERE MAKH = @MAKH) = 0)
	BEGIN
		PRINT 'KHACH HANG KHONG TON TAI'
		ROLLBACK TRAN
		RETURN 
	END
	DECLARE @NGAYLAP DATE
	SET @NGAYLAP = GETDATE()
END TRY
BEGIN CATCH
	PRINT 'THEM HOA DON KHONG THANH CONG'
	ROLLBACK TRAN
END CATCH
	INSERT INTO HOADON VALUES (@MAHD,@MANV,@MAKH,@NGAYLAP,0,0,0)
COMMIT TRAN
GO
--TRIGGER CAP NHAT GIA 
CREATE TRIGGER TRG_GIABAN ON CHITIETHOADON
FOR INSERT
AS
	UPDATE CHITIETHOADON
	SET GIABAN = (SELECT GIA FROM DONGIA WHERE MAHG = (SELECT MAHG FROM inserted))
	WHERE MAHG =(SELECT MAHG FROM inserted)
GO
--TRIGGER CAP NHAP THANH TIEN CHO CTHD
CREATE TRIGGER TRG_TT ON CHITIETHOADON
FOR INSERT, UPDATE
AS
	UPDATE CHITIETHOADON
	SET THANHTIEN = (SELECT GIABAN FROM inserted WHERE MAHD = (SELECT MAHD FROM inserted))*(SELECT SOLUONG FROM inserted  WHERE MAHD = (SELECT MAHD FROM inserted))
	WHERE MAHG =(SELECT MAHG FROM inserted)
GO
--Tao store procedure cho CHI TIET HOA DON
CREATE PROC PR_CTHD @MAHD CHAR(10),@MAHG CHAR(10),@SOLUONG INT
AS
BEGIN TRY
	IF((SELECT COUNT(*) FROM HOADON WHERE MAHD = @MAHD)=0)
	BEGIN
		PRINT 'HOA DON KHONG HOP LE'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT COUNT(*) FROM HANG WHERE MAHG = @MAHG)=0)
	BEGIN
		PRINT 'HANG KHONG HOP LE'
		ROLLBACK TRAN
		RETURN 
	END
	IF(@SOLUONG<0)
	BEGIN
		PRINT 'SOLUONG KHONG HOP LE'
		ROLLBACK TRAN
		RETURN 
	END
	IF((SELECT DBO.FUN_CHECKHANGDU(@MAHG,@SOLUONG))=0)
	BEGIN
		PRINT'SO LUONG HANG KHONG DU'
		ROLLBACK TRAN
		RETURN 
	END 
END TRY
BEGIN CATCH
	PRINT 'THEM THAT BAI'
	ROLLBACK TRAN
END CATCH
	INSERT INTO CHITIETHOADON(MAHD,MAHG,SOLUONG) VALUES (@MAHD,@MAHG,@SOLUONG)
	COMMIT TRAN 
GO
--NHAP LIEU
EXEC PR_NHANVIEN 'NH01',N'Trần Ngọc Khải',N'NAM',N'TP.Bến Tre',N'NHAN VIEN',6000000
EXEC PR_NHANVIEN 'NH02',N'Trần Văn A',N'NAM',N'TP.Bến Tre',N'NHAN VIEN',6000000
EXEC PR_NHANVIEN 'NH03',N'Trần Thị B',N'NU',N'TP.Bến Tre',N'QUAN LY',15000000
EXEC PR_NHANVIEN 'NH04',N'Trần Văn C',N'NAM',N'TP.Bến Tre',N'NHAN VIEN',6000000
EXEC PR_NHANVIEN 'NH05',N'Trần Thị D',N'NU',N'TP.Bến Tre',N'GIAM DOC',20000000

EXEC PR_KHACHHANG 'KH01',N'Nguyễn Văn A',N'TP.HCM',N'NAM','0364651210',0
EXEC PR_KHACHHANG 'KH02',N'Nguyễn Văn B',N'TP.DANANG',N'NAM','0364651210',0
EXEC PR_KHACHHANG 'KH03',N'Nguyễn Văn C',N'TP.VUNG TAU',N'NAM','0364651210',0
EXEC PR_KHACHHANG 'KH04',N'Nguyễn Thị D',N'TP.BEN TRE',N'NU','0364651210',0
EXEC PR_KHACHHANG 'KH05',N'Nguyễn Văn E',N'TP.HCM',N'NAM','0364651210',0

EXEC PR_NHASX 'NSX01',N'nhà sản xuất 1',N'TP.HCM','099998888'
EXEC PR_NHASX 'NSX02',N'nhà sản xuất 2',N'TP.HA NOI','099998888'
EXEC PR_NHASX 'NSX03',N'nhà sản xuất 3',N'TP.HCM','099998888'
EXEC PR_NHASX 'NSX04',N'nhà sản xuất 4',N'TP.BINH DUONG','099998888'
EXEC PR_NHASX 'NSX05',N'nhà sản xuất 5',N'TP.HCM','099998888'

EXEC PR_NHACC'NCC01',N'nhà cung cấp 1',N'TP.HCM','011118888'
EXEC PR_NHACC'NCC02',N'nhà cung cấp 2',N'TP.HA NOI','011118888'
EXEC PR_NHACC'NCC03',N'nhà cung cấp 3',N'TP.HCM','011118888'
EXEC PR_NHACC'NCC04',N'nhà cung cấp 4',N'TP.HA NOI','011118888'
EXEC PR_NHACC'NCC05',N'nhà cung cấp 5',N'TP.HCM','011118888'

EXEC PR_HANG 'HG01',N'điện thoại 1',N'DIEN THOAI',20,'NSX01','NCC01',8
EXEC PR_HANG 'HG02',N'điện thoại 2',N'DIEN THOAI',20,'NSX02','NCC01',8
EXEC PR_HANG 'HG03',N'Lap top',N'LAPTOP',20,'NSX01','NCC01',8
EXEC PR_HANG 'HG04',N'tivi sony',N'TIVI',20,'NSX03','NCC01',8
EXEC PR_HANG 'HG05',N'điện thoại 3',N'DIEN THOAI',20,'NSX01','NCC01',8

EXEC PR_DONGIA 'HG01',50000000
EXEC PR_DONGIA 'HG02',100000000
EXEC PR_DONGIA 'HG03',80000000
EXEC PR_DONGIA 'HG04',90000000
EXEC PR_DONGIA 'HG05',40000000

EXEC PR_GIAMGIA 'HG01','8/24/2020',500000
EXEC PR_GIAMGIA 'HG02','8/24/2020',500000
EXEC PR_GIAMGIA 'HG03','8/24/2020',500000
EXEC PR_GIAMGIA 'HG04','8/24/2020',500000
EXEC PR_GIAMGIA 'HG05','8/24/2020',500000

EXEC PR_PHIEUNHAP 'PN01','NCC01','NSX01'
EXEC PR_PHIEUNHAP 'PN02','NCC01','NSX01'
EXEC PR_PHIEUNHAP 'PN03','NCC01','NSX01'
EXEC PR_PHIEUNHAP 'PN04','NCC01','NSX01'
EXEC PR_PHIEUNHAP 'PN05','NCC01','NSX01'

EXEC PR_CTPN 'PN01','HG01',20
EXEC PR_CTPN 'PN01','HG02',20
EXEC PR_CTPN 'PN01','HG03',20
EXEC PR_CTPN 'PN01','HG04',20
EXEC PR_CTPN 'PN01','HG05',20

EXEC PR_HOADON 'HD01','NH01','KH01'
EXEC PR_HOADON 'HD02','NH02','KH01'
EXEC PR_HOADON 'HD03','NH03','KH01'
EXEC PR_HOADON 'HD04','NH01','KH02'
EXEC PR_HOADON 'HD05','NH01','KH03'

EXEC PR_CTHD 'HD01','HG08',1
EXEC PR_CTHD 'HD02','HG02',1
EXEC PR_CTHD 'HD03','HG04',1
EXEC PR_CTHD 'HD04','HG03',1
EXEC PR_CTHD 'HD05','HG05',2
---thiết lập mô hình
--thứ (lan 1)
backup database QL_DIENMAY
to disk='D:\qldm_diff.bak'
with init, differential
----thứ (lan2 )
backup database QL_DIENMAY
to disk='D:\qldm_diff.bak'
with differential
---log lan 1
backup log QL_DIENMAY
to disk='D:\log_ql.trn'
with init ,description='QL_DIENMAY Log backup'
--full
Backup database QL_DIENMAY
to Disk ='D:\qldm_full.bak'
with init, description='backup database QL_DIENMAY '

-- nếu bị mất dữ liệu
---phuc hoi 
--backup log tail
backup log QL_DIENMAY
to disk='D:\log_ql.trn'
with NO_TRUNCATE
-- phuc hoi full
 restore database QL_DIENMAY
 from disk='D:\qldm_full.bak'
 with replace, norecovery
 ---p hồi diff gần nhất
 restore database QL_DIENMAY
 from disk='D:\qldm_diff.bak'
 with file=2, norecovery
 --- phục hồi tập tin thứ 1,
 restore database QL_DIENMAY
 from disk='D:\log_ql.trn'
 with file=1, norecovery
 --phục hồi tập tin thứ 2,tail 
 restore database QL_DIENMAY
 from disk='D:\log_ql.trn'
 with file=2,recovery

 --phân quyền
SP_ADDROLE 'BOSS'
SP_ADDROLE 'NHANVIEN'
SP_ADDROLE 'KHACH'
--boss có toàn quyền trên cơ sở dữ liệu
GRANT ALL
ON NHANVIEN TO BOSS
GRANT ALL
ON KHACHHANG TO BOSS
GRANT ALL
ON NHASX TO BOSS
GRANT ALL
ON NHACC TO BOSS
GRANT ALL
ON HANG TO BOSS
GRANT ALL
ON DONGIA TO BOSS
GRANT ALL
ON PHIEUNHAP TO BOSS
GRANT ALL
ON CHITIETPHIEUNHAP TO BOSS
GRANT ALL
ON HOADON TO BOSS
GRANT ALL
ON CHITIETHOADON TO BOSS
GRANT ALL
ON PHIEUBAOHANH TO BOSS
GRANT ALL
ON GIAMGIA TO BOSS
--khách hàng có quyền xem hàng
GRANT SELECT 
ON HANG TO KHACH
--nhân viên có xem hàng, thêm hóa đơn
GRANT SELECT 
ON HANG TO NHANVIEN
GRANT SELECT,UPDATE,INSERT
ON HOADON TO NHANVIEN
GRANT SELECT,UPDATE,INSERT
ON CHITIETHOADON TO NHANVIEN

SP_ADDLOGIN 'BOSS','1234'
SP_ADDLOGIN 'NHANVIEN','12345'
SP_ADDLOGIN 'KHACH','123'

SP_ADDUSER 'BOSS','BOSS'
SP_ADDUSER 'NHANVIEN','NHANVIEN'
SP_ADDUSER 'KHACH','KHACH'

SP_ADDROLEMEMBER 'BOSS','BOSS'
SP_ADDROLEMEMBER 'NHANVIEN','NHANVIEN'
SP_ADDROLEMEMBER 'KHACH','KHACH'